// ============================================
// COMPARE - Output Generators
// ============================================

import {
  SnapshotComparison,
  ComparisonMatrix,
  ComparisonDimension,
  ComparisonScore
} from './types'

// ============================================
// MAIN GENERATOR EXPORT
// ============================================

export async function generateAllOutputs(
  comparison: SnapshotComparison
): Promise<{
  report: string
  matrix: ComparisonMatrix
}> {
  return {
    report: generateCompareReport(comparison),
    matrix: generateComparisonMatrix(comparison)
  }
}

// ============================================
// REPORT GENERATOR
// ============================================

export function generateCompareReport(comparison: SnapshotComparison): string {
  const { meta, visualDiff, uxComparison, opportunities, recommendations } = comparison

  return `
# Snapshot Comparison Report

**Generated:** ${meta.comparedAt}
**Snapshots Compared:** ${meta.snapshotCount}

## URLs Compared

${meta.urls.map((url, i) => `${i + 1}. ${meta.names[i]}: ${url}`).join('\n')}

## Summary

**Total Differences:** ${meta.totalDifferences}
**Major Changes:** ${meta.majorChanges.length}

### Major Changes

${meta.majorChanges.length > 0 ?
  meta.majorChanges.map(change =>
    `### ${change.type.toUpperCase()}: ${change.description}\n**Impact:** ${change.impact}`
  ).join('\n\n') :
  'No major changes detected.'
}

---

## Visual Changes

**Total Changes:** ${visualDiff.summary.totalChanges}
- High Impact: ${visualDiff.summary.highImpact}
- Medium Impact: ${visualDiff.summary.mediumImpact}
- Low Impact: ${visualDiff.summary.lowImpact}

### Categories Changed
${visualDiff.summary.categoriesChanged.map(c => `- ${c}`).join('\n') || 'None'}

### Layout Changes
${visualDiff.layoutChanges.length > 0 ?
  visualDiff.layoutChanges.map(change =>
    `- **${change.type}:** ${change.description} (${change.impact} impact)`
  ).join('\n') :
  'No layout changes detected.'
}

### Component Changes
${visualDiff.componentChanges.length > 0 ?
  visualDiff.componentChanges.map(change =>
    `- **${change.component}:** ${change.action} - ${change.description}`
  ).join('\n') :
  'No component changes detected.'
}

---

## UX Comparison

### Flow Changes
${uxComparison.flowChanges.length > 0 ?
  uxComparison.flowChanges.map(flow =>
    `- **${flow.flowName}:** ${flow.action} (${flow.stepsBefore} → ${flow.stepsAfter} steps)`
  ).join('\n') :
  'No flow changes detected.'
}

### Accessibility
**Before:** ${uxComparison.accessibilityComparison.scoreBefore}/100
**After:** ${uxComparison.accessibilityComparison.scoreAfter}/100

${uxComparison.accessibilityComparison.improvements.length > 0 ?
  '**Improvements:**\n' + uxComparison.accessibilityComparison.improvements.map(i => `- ${i}`).join('\n') : ''
}
${uxComparison.accessibilityComparison.regressions.length > 0 ?
  '**Regressions:**\n' + uxComparison.accessibilityComparison.regressions.map(r => `- ${r}`).join('\n') : ''
}

### Usability
- **Complexity:** ${uxComparison.usabilityComparison.complexityBefore} → ${uxComparison.usabilityComparison.complexityAfter}
- **Cognitive Load:** ${uxComparison.usabilityComparison.cognitiveLoad}

---

## Opportunities

${opportunities.length > 0 ?
  opportunities.map((opp, i) =>
    `### ${i + 1}. ${opp.title}

**Category:** ${opp.category}
**Impact:** ${opp.impact} | **Effort:** ${opp.effort} | **Priority:** ${opp.priority}

${opp.description}
  `
  ).join('\n\n') :
  'No opportunities identified.'
}

---

## Recommendations

${recommendations.length > 0 ?
  recommendations.map((rec, i) =>
    `### ${i + 1}. ${rec.title}

**Type:** ${rec.type}
**Impact:** ${rec.impact} | **Effort:** ${rec.effort}

${rec.description}

**Rationale:** ${rec.rationale}
  `
  ).join('\n\n') :
  'No recommendations at this time.'
}

---

*Generated by SnappyCrawler Compare Mode*
  `.trim()
}

// ============================================
// COMPARISON MATRIX GENERATOR
// ============================================

export function generateComparisonMatrix(comparison: SnapshotComparison): ComparisonMatrix {
  const dimensions = defineComparisonDimensions()
  const scores = calculateDimensionScores(comparison, dimensions)

  return {
    dimensions,
    scores
  }
}

function defineComparisonDimensions(): ComparisonDimension[] {
  return [
    {
      name: 'Visual Complexity',
      weight: 0.8,
      category: 'visual'
    },
    {
      name: 'Design Consistency',
      weight: 0.9,
      category: 'visual'
    },
    {
      name: 'UX Flow Efficiency',
      weight: 1.0,
      category: 'ux'
    },
    {
      name: 'Interaction Quality',
      weight: 0.9,
      category: 'ux'
    },
    {
      name: 'Content Clarity',
      weight: 0.8,
      category: 'content'
    },
    {
      name: 'Messaging Effectiveness',
      weight: 0.7,
      category: 'content'
    },
    {
      name: 'Code Quality',
      weight: 0.9,
      category: 'technical'
    },
    {
      name: 'Performance',
      weight: 1.0,
      category: 'technical'
    }
  ]
}

function calculateDimensionScores(
  comparison: SnapshotComparison,
  dimensions: ComparisonDimension[]
): ComparisonScore[] {
  const scores: ComparisonScore[] = []

  dimensions.forEach(dimension => {
    comparison.meta.urls.forEach((_, index) => {
      const score = calculateScoreForDimension(comparison, dimension.name, index)
      scores.push({
        snapshotIndex: index,
        dimension: dimension.name,
        score: score.raw,
        normalizedScore: score.normalized,
        notes: score.notes
      })
    })
  })

  return scores
}

function calculateScoreForDimension(
  comparison: SnapshotComparison,
  dimensionName: string,
  snapshotIndex: number
): { raw: number; normalized: number; notes: string } {
  // Simplified scoring logic
  // Real implementation would use more sophisticated analysis

  let raw = 50
  let notes = ''

  switch (dimensionName) {
    case 'UX Flow Efficiency':
      raw = comparison.uxComparison.accessibilityComparison.scoreAfter
      notes = `Based on accessibility score of ${raw}`
      break

    case 'Code Quality':
      const complexity = comparison.technicalComparison.codeComplexity
      if (complexity.complexityChange === 'simpler') {
        raw = 80
        notes = 'Code complexity reduced'
      } else if (complexity.complexityChange === 'more-complex') {
        raw = 40
        notes = 'Code complexity increased'
      } else {
        raw = 60
        notes = 'Code complexity unchanged'
      }
      break

    default:
      raw = 50
      notes = 'No specific data available'
  }

  return {
    raw,
    normalized: Math.min(100, Math.max(0, raw)),
    notes
  }
}

// ============================================
// UTILITIES
// ============================================

export function formatChangeSummary(comparison: SnapshotComparison): string {
  const { meta, visualDiff, uxComparison } = comparison

  return `
${meta.snapshotCount} snapshots compared
${meta.totalDifferences} total differences
${visualDiff.summary.totalChanges} visual changes
${uxComparison.flowChanges.length} flow changes
  `.trim()
}

export function getMajorChangesOnly(comparison: SnapshotComparison): any[] {
  return comparison.meta.majorChanges.filter(c => c.impact === 'high')
}

export function getHighImpactOpportunities(comparison: SnapshotComparison): any[] {
  return comparison.opportunities.filter(o => o.impact === 'high')
}

export function getTopRecommendations(comparison: SnapshotComparison, limit = 5): any[] {
  return comparison.recommendations
    .sort((a, b) => a.priority - b.priority)
    .slice(0, limit)
}
