// ============================================
// AI CONTEXT PACK - Output Generators
// ============================================

import {
  AIContextOutput,
  SystemPrompts
} from './types'

// ============================================
// MAIN GENERATOR EXPORT
// ============================================

export async function generateAllOutputs(
  aiContext: AIContextOutput
): Promise<{
  systemBrief: string
  constraintsJSON: string
  codeSchemaJSON: string
  tasksJSON: string
  systemPrompts: SystemPrompts
}> {
  return {
    systemBrief: generateSystemBriefMarkdown(aiContext),
    constraintsJSON: generateConstraintsJSON(aiContext),
    codeSchemaJSON: generateCodeSchemaJSON(aiContext),
    tasksJSON: generateTasksJSON(aiContext),
    systemPrompts: aiContext.systemPrompts
  }
}

// ============================================
// MARKDOWN GENERATORS
// ============================================

export function generateSystemBriefMarkdown(aiContext: AIContextOutput): string {
  const { systemBrief, meta } = aiContext

  return `
# System Brief

## Overview

**Page:** ${systemBrief.overview.pageTitle}
**URL:** ${systemBrief.overview.url}
**Type:** ${systemBrief.overview.pageType}

### Primary Purpose
${systemBrief.overview.primaryPurpose}

### Target Users
${systemBrief.overview.targetUsers.map(u => `- ${u}`).join('\n')}

### Core Value
${systemBrief.overview.coreValue}

## Context

**Domain:** ${systemBrief.context.businessDomain}
${systemBrief.context.industryVertical ? `**Industry:** ${systemBrief.context.industryVertical}` : ''}
**Stage:** ${systemBrief.context.companyStage}
**Position:** ${systemBrief.context.marketPosition}

## Objectives

${systemBrief.objectives.map(obj => `
### ${obj.priority.toUpperCase()}: ${obj.goal}

- **Success Metric:** ${obj.successMetric}
- **User Impact:** ${obj.userImpact}
`).join('\n')}

## Constraints

${systemBrief.constraints.map(con => `
### ${con.type}: ${con.description}

**Reason:** ${con.reason}
${con.alternatives.length > 0 ? `**Alternatives:** ${con.alternatives.join(', ')}` : ''}
`).join('\n')}

## Assumptions

${systemBrief.assumptions.map(assumption => `
### ${assumption.category} (Confidence: ${assumption.confidence})

**Assumption:** ${assumption.assumption}
**Validation:** ${assumption.validationMethod}
**Impact if Wrong:** ${assumption.impactIfWrong}
`).join('\n')}

---

*Generated by SnappyCrawler AI Context Pack*
*Source: ${meta.sourceUrl}*
*Generated: ${meta.generatedAt}*
  `.trim()
}

// ============================================
// JSON GENERATORS
// ============================================

export function generateConstraintsJSON(aiContext: AIContextOutput): string {
  return JSON.stringify(aiContext.constraints, null, 2)
}

export function generateCodeSchemaJSON(aiContext: AIContextOutput): string {
  return JSON.stringify(aiContext.codeSchema, null, 2)
}

export function generateTasksJSON(aiContext: AIContextOutput): string {
  return JSON.stringify(aiContext.suggestedTasks, null, 2)
}

// ============================================
// FULL OUTPUT GENERATOR
// ============================================

export function generateFullContext(aiContext: AIContextOutput): string {
  return `
{
  "meta": ${JSON.stringify(aiContext.meta, null, 2)},
  "systemBrief": ${JSON.stringify(aiContext.systemBrief, null, 2)},
  "constraints": ${JSON.stringify(aiContext.constraints, null, 2)},
  "codeSchema": ${JSON.stringify(aiContext.codeSchema, null, 2)},
  "suggestedTasks": ${JSON.stringify(aiContext.suggestedTasks, null, 2)}
}
  `.trim()
}

// ============================================
// UTILITIES
// ============================================

export function formatSystemPrompt(
  prompt: string,
  variables: Record<string, string> = {}
): string {
  let formatted = prompt

  Object.entries(variables).forEach(([key, value]) => {
    formatted = formatted.replace(new RegExp(`\\{\\{${key}\\}\\}`, 'g'), value)
  })

  return formatted
}

export function getPromptByRole(
  aiContext: AIContextOutput,
  role: 'developer' | 'designer' | 'pm' | 'llm' | 'generic'
): string {
  return aiContext.systemPrompts[role] || aiContext.systemPrompts.generic
}
