'use client'

import { useCallback, useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Upload } from 'lucide-react'
import { RawSnapshot } from '@/lib/types'

interface SnapshotUploaderProps {
  onUpload: (snapshot: RawSnapshot) => void
}

export function SnapshotUploader({ onUpload }: SnapshotUploaderProps) {
  const [isDragging, setIsDragging] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const handleFile = useCallback((file: File) => {
    setError(null)

    // Validate file type
    if (!file.name.endsWith('.json')) {
      setError('Please upload a JSON file')
      return
    }

    // Read and parse file
    const reader = new FileReader()

    reader.onload = (e) => {
      try {
        const content = e.target?.result as string
        const snapshot = JSON.parse(content) as RawSnapshot

        // Validate snapshot structure
        if (!snapshot.url || !snapshot.html || !Array.isArray(snapshot.text)) {
          setError('Invalid snapshot format')
          return
        }

        onUpload(snapshot)
      } catch (err) {
        setError('Failed to parse JSON file')
        console.error('Parse error:', err)
      }
    }

    reader.readAsText(file)
  }, [onUpload])

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(true)
  }, [])

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(false)
  }, [])

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setIsDragging(false)

    const files = Array.from(e.dataTransfer.files)
    if (files.length > 0) {
      handleFile(files[0])
    }
  }, [handleFile])

  const handleFileInput = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files
    if (files && files.length > 0) {
      handleFile(files[0])
    }
  }, [handleFile])

  return (
    <Card
      className={`transition-all ${
        isDragging
          ? 'border-primary border-2 bg-primary/5'
          : 'border-dashed'
      }`}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
    >
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Upload className="w-5 h-5" />
          Upload Snapshot
        </CardTitle>
        <CardDescription>
          Drag & drop a snapshot JSON file or click to browse
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex flex-col items-center justify-center py-8">
          <Upload className="w-12 h-12 text-muted-foreground mb-4" />
          <p className="text-sm text-muted-foreground text-center mb-4">
            Upload a snapshot file generated by the Snappy extension
          </p>
          <label>
            <input
              type="file"
              accept=".json"
              className="hidden"
              onChange={handleFileInput}
            />
            <Button asChild>
              <span>Choose File</span>
            </Button>
          </label>
        </div>

        {error && (
          <div className="p-4 bg-destructive/10 border border-destructive rounded-md">
            <p className="text-sm text-destructive">{error}</p>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
